library(shiny)
library(shinythemes)
library(lubridate)

# Define UI for application that draws a histogram
shinyUI(fluidPage(theme = shinytheme("slate"),
  
  # Application title
  titlePanel("Optimal roulette strategy!"),
  
  sidebarLayout(
 #   titlePanel("Chose between options below"),
    sidebarPanel(
      fileInput("load", "Continue with previous game"),
      actionButton("apply", "Apply")
    ),
    mainPanel(
      textOutput("start")
    )
  ),
 sidebarLayout(
   sidebarPanel(
     radioButtons("currency", "Choose a currency", choices = list("Euro", "Dollar")),
     textInput("value", "How much money do you want to put in?"),
     actionButton("insert", "Insert")
   ),
   mainPanel(
     textOutput("money")
   )
 ),
 
# denar <-  
 
  fluidRow(
    column(1,
           wellPanel(sliderInput("bet3", "Number 3", value = 0, min=0, max=10000),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet6", "Bet on number 6", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet9", "Bet on number 9", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet12", "Bet on number 12", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet15", "Bet on number 15", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet18", "Bet on number 18", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet21", "Bet on number 21", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet24", "Bet on number 24", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet27", "Bet on number 27", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet30", "Bet on number 30", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet33", "Bet on number 33", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet36", "Bet on number 36", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet2", "Bet on number 2", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet5", "Bet on number 5", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet8", "Bet on number 8", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet11", "Bet on number 11", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet14", "Bet on number 14", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet17", "Bet on number 17", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet20", "Bet on number 20", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet23", "Bet on number 23", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet26", "Bet on number 26", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet29", "Bet on number 29", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet32", "Bet on number 32", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet35", "Bet on number 35", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet1", "Bet on number 1", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet4", "Bet on number 4", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet7", "Bet on number 7", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet10", "Bet on number 10", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet13", "Bet on number 13", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet16", "Bet on number 16", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet19", "Bet on number 19", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet22", "Bet on number 22", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet25", "Bet on number 25", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(1, 
           wellPanel(numericInput("bet28", "Bet on number 28", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet31", "Bet on number 31", value = 0, min=0, max=100),
                     style="background: black")),
    column(1, 
           wellPanel(numericInput("bet34", "Bet on number 34", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(2, 
           wellPanel(numericInput("betEven", "Bet on even", value = 0, min=0, max=100))),
    column(2, 
           wellPanel(numericInput("betRed", "Bet on red", value = 0, min=0, max=100),
                     style="background: firebrick")),
    column(2, 
           wellPanel(numericInput("bet00", "Bet on 00", value = 0, min=0, max=100),
                     style="background: green")),
    column(2, 
           wellPanel(numericInput("bet0", "Bet on 0", value = 0, min=0, max=100),
                     style="background: green")),
    column(2, 
           wellPanel(numericInput("betBlack", "Bet on black", value = 0, min=0, max=100),
                     style="background: black")),
    column(2, 
           wellPanel(numericInput("betOdd", "Bet on odd", value = 0, min=0, max=100)))
  ),
  hr(),
  fluidRow(
    column(12,
           actionButton('start','Start'),
           actionButton('stop','Stop'),
           textOutput('timeleft')),
    column(6, 
           wellPanel(
             h3("Podajte stavo"),
             sliderInput(inputId = "bet",
                         label = "Bet", sep = "",
                         value = 0, min = 0, max = 10, step = 1),
             br(),
             selectInput(inputId = "number",
                         label = "Number",
                         choices = c("00", "0", c(1:36)),
                         multiple = FALSE),
             br(),
             actionButton("stava", "Stavi")
           )),
    column(6, 
           wellPanel(
             textOutput("sta"))),
    column(12, 
           wellPanel(
             actionButton("roll", "Roll the whell!"), 
             textOutput("num")
           ))
  )
  
  )
)
